//go:build ignore
// +build ignore

// Code generated by docs/examplegen; DO NOT EDIT.

package main

import (
	"os"
	"path/filepath"

	"github.com/goforj/env/v2"
)

// main keeps this documented example executable so API drift fails during compilation.
func main() {
	// Load loads the nearest env files with deterministic layering.
	//
	// Load applies once per process. Existing process values override files, and later files override
	// earlier files for keys absent from the process environment. Discovery and parsing complete
	// before the process environment changes; errors leave both the environment and loader state
	// unchanged. Use Reload to re-read files.

	// Example: test-specific env file
	tmp, _ := os.MkdirTemp("", "envdoc")
	defer os.RemoveAll(tmp)
	originalDirectory, _ := os.Getwd()
	defer os.Chdir(originalDirectory)
	_ = os.WriteFile(filepath.Join(tmp, ".env.testing"), []byte("PORT=9090\nENV_DEBUG=0"), 0o644)
	_ = os.Chdir(tmp)
	_ = os.Setenv("APP_ENV", env.Testing)

	_ = env.Load()
	env.Dump(os.Getenv("PORT"))
	// #string "9090"
}
