//go:build ignore
// +build ignore

// Code generated by docs/examplegen; DO NOT EDIT.

package main

import "github.com/goforj/env/v2"

// main keeps this documented example executable so API drift fails during compilation.
func main() {
	// IsContainerOS reports whether this OS is *typically* used as a container base.

	env.Dump(env.IsContainerOS())
	// #bool true  (on Linux)
	// #bool false (on macOS/Windows)
}
