//go:build ignore
// +build ignore

// Code generated by docs/examplegen; DO NOT EDIT.

package main

import (
	"os"
	"path/filepath"

	"github.com/goforj/env/v2"
)

// main keeps this documented example executable so API drift fails during compilation.
func main() {
	// Reload re-discovers and transactionally reapplies env files even after Load has run.
	//
	// Keys loaded from files remain file-owned: Reload replaces runtime edits to those keys. When a
	// key disappears from all files, Reload restores the ambient value (including unset versus empty)
	// that existed before the first successful Load. Unrelated process variables are never changed.

	// Example: refresh changed env files
	tmp, _ := os.MkdirTemp("", "envdoc")
	defer os.RemoveAll(tmp)
	originalDirectory, _ := os.Getwd()
	defer os.Chdir(originalDirectory)
	_ = os.Chdir(tmp)
	_ = os.WriteFile(filepath.Join(tmp, ".env"), []byte("SERVICE=api"), 0o644)
	_ = env.Load()
	_ = os.WriteFile(filepath.Join(tmp, ".env"), []byte("SERVICE=worker"), 0o644)
	_ = env.Reload()
	env.Dump(os.Getenv("SERVICE"))
	// #string "worker"
}
