//go:build ignore
// +build ignore

// Code generated by docs/examplegen; DO NOT EDIT.

package main

import (
	"os"

	"github.com/goforj/env/v2"
)

// main keeps this documented example executable so API drift fails during compilation.
func main() {
	// GetDuration parses a Go duration string (e.g. "5s", "10m", "1h").

	// Example: override request timeout
	_ = os.Setenv("HTTP_TIMEOUT", "30s")
	timeout := env.GetDuration("HTTP_TIMEOUT", "5s")
	env.Dump(timeout)
	// #time.Duration 30s

	// Example: fallback when unset
	os.Unsetenv("HTTP_TIMEOUT")
	timeout = env.GetDuration("HTTP_TIMEOUT", "5s")
	env.Dump(timeout)
	// #time.Duration 5s
}
