//go:build ignore
// +build ignore

// Code generated by docs/examplegen; DO NOT EDIT.

package main

import "github.com/goforj/env/v2"

// main keeps this documented example executable so API drift fails during compilation.
func main() {
	// IsUnix reports whether the OS is Unix-like.

	env.Dump(env.IsUnix())
	// #bool true  (on Unix-like OSes)
	// #bool false (e.g., on Windows or Plan 9)
}
