//go:build ignore
// +build ignore

// Code generated by docs/examplegen; DO NOT EDIT.

package main

import (
	"os"

	"github.com/goforj/env/v2"
)

// main keeps this documented example executable so API drift fails during compilation.
func main() {
	// IsAppEnvTesting reports whether APP_ENV is "testing" or the process looks like `go test`.

	// Example: APP_ENV explicitly testing
	_ = os.Setenv("APP_ENV", env.Testing)
	env.Dump(env.IsAppEnvTesting())
	// #bool true

	// Example: no test markers
	_ = os.Unsetenv("APP_ENV")
	env.Dump(env.IsAppEnvTesting())
	// #bool false (outside of test binaries)
}
