//go:build ignore
// +build ignore

// Code generated by docs/examplegen; DO NOT EDIT.

package main

import "github.com/goforj/env/v2"

// main keeps this documented example executable so API drift fails during compilation.
func main() {
	// SetAppEnvStaging sets APP_ENV to "staging".

	_ = env.SetAppEnvStaging()
	env.Dump(env.GetAppEnv())
	// #string "staging"
}
