//go:build ignore
// +build ignore

// Code generated by docs/examplegen; DO NOT EDIT.

package main

import "github.com/goforj/env/v2"

// main keeps this documented example executable so API drift fails during compilation.
func main() {
	// IsDockerHost reports whether this container behaves like a Docker host.

	env.Dump(env.IsDockerHost())
	// #bool true  (when acting as Docker host)
	// #bool false (for normal containers/hosts)
}
