//go:build ignore
// +build ignore

// Code generated by docs/examplegen; DO NOT EDIT.

package main

import (
	"os"

	"github.com/goforj/env/v2"
)

// main keeps this documented example executable so API drift fails during compilation.
func main() {
	// GetFloat parses a float64 from an environment variable or fallback string.

	// Example: override threshold
	_ = os.Setenv("THRESHOLD", "0.82")
	threshold := env.GetFloat("THRESHOLD", "0.75")
	env.Dump(threshold)
	// #float64 0.82

	// Example: fallback with decimal string
	os.Unsetenv("THRESHOLD")
	threshold = env.GetFloat("THRESHOLD", "0.75")
	env.Dump(threshold)
	// #float64 0.75
}
