//go:build ignore
// +build ignore

// Code generated by docs/examplegen; DO NOT EDIT.

package main

import (
	"os"

	"github.com/goforj/env/v2"
)

// main keeps this documented example executable so API drift fails during compilation.
func main() {
	// IsAppEnvStaging checks if APP_ENV is "staging".

	_ = os.Setenv("APP_ENV", env.Staging)
	env.Dump(env.IsAppEnvStaging())
	// #bool true
}
