//go:build ignore
// +build ignore

// Code generated by docs/examplegen; DO NOT EDIT.

package main

import "github.com/goforj/env/v2"

// main keeps this documented example executable so API drift fails during compilation.
func main() {
	// IsLinux reports whether the runtime OS is Linux.

	env.Dump(env.IsLinux())
	// #bool true  (on Linux)
	// #bool false (on other OSes)
}
