//go:build ignore
// +build ignore

// Code generated by docs/examplegen; DO NOT EDIT.

package main

import (
	"os"

	"github.com/goforj/env/v2"
)

// main keeps this documented example executable so API drift fails during compilation.
func main() {
	// GetBool parses a boolean from an environment variable or fallback string.

	// Example: numeric truthy
	_ = os.Setenv("DEBUG", "1")
	debug := env.GetBool("DEBUG", "false")
	env.Dump(debug)
	// #bool true

	// Example: fallback string
	os.Unsetenv("DEBUG")
	debug = env.GetBool("DEBUG", "false")
	env.Dump(debug)
	// #bool false
}
