//go:build ignore
// +build ignore

// Code generated by docs/examplegen; DO NOT EDIT.

package main

import "github.com/goforj/env/v2"

// main keeps this documented example executable so API drift fails during compilation.
func main() {
	// Arch returns the CPU architecture the binary is running on.

	// Example: print GOARCH
	env.Dump(env.Arch())
	// #string "amd64"
	// #string "arm64"
}
