//go:build ignore
// +build ignore

// Code generated by docs/examplegen; DO NOT EDIT.

package main

import "github.com/goforj/env/v2"

// main keeps this documented example executable so API drift fails during compilation.
func main() {
	// IsKubernetes reports whether the process is running inside Kubernetes.

	env.Dump(env.IsKubernetes())
	// #bool true  (inside Kubernetes pods)
	// #bool false (elsewhere)
}
