//go:build ignore
// +build ignore

// Code generated by docs/examplegen; DO NOT EDIT.

package main

import (
	"os"

	"github.com/goforj/env/v2"
)

// main keeps this documented example executable so API drift fails during compilation.
func main() {
	// GetInt64 parses an int64 from an environment variable or fallback string.

	// Example: parse large numbers safely
	_ = os.Setenv("MAX_SIZE", "1048576")
	size := env.GetInt64("MAX_SIZE", "512")
	env.Dump(size)
	// #int64 1048576

	// Example: fallback when unset
	os.Unsetenv("MAX_SIZE")
	size = env.GetInt64("MAX_SIZE", "512")
	env.Dump(size)
	// #int64 512
}
