//go:build ignore
// +build ignore

// Code generated by docs/examplegen; DO NOT EDIT.

package main

import "github.com/goforj/env/v2"

// main keeps this documented example executable so API drift fails during compilation.
func main() {
	// SetAppEnv sets APP_ENV to a supported value.

	// Example: set a supported environment
	_ = env.SetAppEnv(env.Staging)
	env.Dump(env.GetAppEnv())
	// #string "staging"
}
