//go:build ignore
// +build ignore

// Code generated by docs/examplegen; DO NOT EDIT.

package main

import (
	"os"

	"github.com/goforj/env/v2"
)

// main keeps this documented example executable so API drift fails during compilation.
func main() {
	// GetUint parses a uint from an environment variable or fallback string.

	// Example: defaults to fallback when missing
	os.Unsetenv("WORKERS")
	workers := env.GetUint("WORKERS", "4")
	env.Dump(workers)
	// #uint 4

	// Example: uses provided unsigned value
	_ = os.Setenv("WORKERS", "16")
	workers = env.GetUint("WORKERS", "4")
	env.Dump(workers)
	// #uint 16
}
