//go:build ignore
// +build ignore

// Code generated by docs/examplegen; DO NOT EDIT.

package main

import "github.com/goforj/env/v2"

// main keeps this documented example executable so API drift fails during compilation.
func main() {
	// IsBSD reports whether the runtime OS is any BSD variant.

	env.Dump(env.IsBSD())
	// #bool true  (on BSD variants)
	// #bool false (elsewhere)
}
