//go:build ignore
// +build ignore

// Code generated by docs/examplegen; DO NOT EDIT.

package main

import "github.com/goforj/env/v2"

// main keeps this documented example executable so API drift fails during compilation.
func main() {
	// IsWindows reports whether the runtime OS is Windows.

	env.Dump(env.IsWindows())
	// #bool true  (on Windows)
	// #bool false (elsewhere)
}
