//go:build ignore
// +build ignore

// Code generated by docs/examplegen; DO NOT EDIT.

package main

import (
	"os"

	"github.com/goforj/env/v2"
)

// main keeps this documented example executable so API drift fails during compilation.
func main() {
	// IsAppEnv checks if APP_ENV matches any of the provided environments.

	// Example: match any allowed environment
	_ = os.Setenv("APP_ENV", "staging")
	env.Dump(env.IsAppEnv(env.Production, env.Staging))
	// #bool true

	// Example: unmatched environment
	_ = os.Setenv("APP_ENV", "local")
	env.Dump(env.IsAppEnv(env.Production, env.Staging))
	// #bool false
}
