//go:build ignore
// +build ignore

// Code generated by docs/examplegen; DO NOT EDIT.

package main

import (
	"os"

	"github.com/goforj/env/v2"
)

// main keeps this documented example executable so API drift fails during compilation.
func main() {
	// GetAppEnv returns the current APP_ENV (empty string if unset).

	// Example: simple retrieval
	_ = os.Setenv("APP_ENV", "staging")
	env.Dump(env.GetAppEnv())
	// #string "staging"
}
