//go:build ignore
// +build ignore

// Code generated by docs/examplegen; DO NOT EDIT.

package main

import (
	"os"

	"github.com/goforj/env/v2"
)

// main keeps this documented example executable so API drift fails during compilation.
func main() {
	// MustGetBool returns a required bool or panics when the value is missing or invalid.

	// Example: gate features explicitly
	_ = os.Setenv("FEATURE_ENABLED", "true")
	enabled := env.MustGetBool("FEATURE_ENABLED")
	env.Dump(enabled)
	// #bool true

	// Example: panic on invalid value
	_ = os.Setenv("FEATURE_ENABLED", "maybe")
	_ = env.MustGetBool("FEATURE_ENABLED") // panics when parsing
}
