//go:build ignore
// +build ignore

// Code generated by docs/examplegen; DO NOT EDIT.

package main

import "github.com/goforj/env/v2"

// main keeps this documented example executable so API drift fails during compilation.
func main() {
	// IsHostEnvironment reports whether the process is running *outside* any
	// container or orchestrated runtime.

	env.Dump(env.IsHostEnvironment())
	// #bool true  (on bare-metal/VM hosts)
	// #bool false (inside containers)
}
