//go:build ignore
// +build ignore

// Code generated by docs/examplegen; DO NOT EDIT.

package main

import (
	"os"

	"github.com/goforj/env/v2"
)

// main keeps this documented example executable so API drift fails during compilation.
func main() {
	// GetInt parses an int from an environment variable or fallback string.

	// Example: fallback used
	os.Unsetenv("PORT")
	port := env.GetInt("PORT", "3000")
	env.Dump(port)
	// #int 3000

	// Example: env overrides fallback
	_ = os.Setenv("PORT", "8080")
	port = env.GetInt("PORT", "3000")
	env.Dump(port)
	// #int 8080
}
