//go:build ignore
// +build ignore

// Code generated by docs/examplegen; DO NOT EDIT.

package main

import "github.com/goforj/env/v2"

// main keeps this documented example executable so API drift fails during compilation.
func main() {
	// Dump writes complete representations of its arguments to standard output.

	// Example: integers
	nums := []int{1, 2, 3}
	env.Dump(nums)
	// #[]int [
	//   0 => 1 #int
	//   1 => 2 #int
	//   2 => 3 #int
	// ]

	// Example: multiple values
	env.Dump("status", map[string]int{"ok": 1, "fail": 0})
	// #string "status"
	// #map[string]int [
	//   "fail" => 0 #int
	//   "ok"   => 1 #int
	// ]
}
