//go:build ignore
// +build ignore

// Code generated by docs/examplegen; DO NOT EDIT.

package main

import "github.com/goforj/env/v2"

// main keeps this documented example executable so API drift fails during compilation.
func main() {
	// IsContainer detects common container runtimes (Docker, containerd, Kubernetes, Podman).

	// Example: host vs container
	env.Dump(env.IsContainer())
	// #bool true  (inside most containers)
	// #bool false (on bare-metal/VM hosts)
}
