//go:build ignore
// +build ignore

// Code generated by docs/examplegen; DO NOT EDIT.

package main

import "github.com/goforj/env/v2"

// main keeps this documented example executable so API drift fails during compilation.
func main() {
	// OS returns the current operating system identifier.

	// Example: inspect GOOS
	env.Dump(env.OS())
	// #string "linux"   (on Linux)
	// #string "darwin"  (on macOS)
	// #string "windows" (on Windows)
}
