//go:build ignore
// +build ignore

// Code generated by docs/examplegen; DO NOT EDIT.

package main

import (
	"os"

	"github.com/goforj/env/v2"
)

// main keeps this documented example executable so API drift fails during compilation.
func main() {
	// MustGetInt returns a required int or panics when the value is missing or invalid.

	// Example: ensure numeric port
	_ = os.Setenv("PORT", "8080")
	port := env.MustGetInt("PORT")
	env.Dump(port)
	// #int 8080

	// Example: panic on bad value
	_ = os.Setenv("PORT", "not-a-number")
	_ = env.MustGetInt("PORT") // panics when parsing
}
