//go:build ignore
// +build ignore

package main

import (
	"bytes"
	"errors"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

const generatedMarker = "// Code generated by docs/examplegen; DO NOT EDIT."

// main renders the reproducible documentation artifacts for this module.
func main() {
	if err := run(); err != nil {
		fmt.Println("Error:", err)
		os.Exit(1)
	}
	fmt.Println("✔ Examples generated in ./examples/")
}

// run regenerates the exact set of documented examples and removes only stale generated entrypoints.
func run() error {
	root, err := findRoot()
	if err != nil {
		return err
	}

	examplesDir := filepath.Join(root, "examples")
	if err := os.MkdirAll(examplesDir, 0o755); err != nil {
		return err
	}

	modPath, err := modulePath(root)
	if err != nil {
		return err
	}

	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, root, nil, parser.ParseComments)
	if err != nil {
		return err
	}

	pkgName, err := selectPackage(pkgs)
	if err != nil {
		return err
	}

	pkg, ok := pkgs[pkgName]
	if !ok {
		return fmt.Errorf(`package %q not found in %s`, pkgName, root)
	}

	funcs := map[string]*FuncDoc{}

	filenames := make([]string, 0, len(pkg.Files))
	for filename := range pkg.Files {
		filenames = append(filenames, filename)
	}
	sort.Strings(filenames)
	for _, filename := range filenames {
		file := pkg.Files[filename]
		if strings.Contains(filename, "_test.go") {
			continue
		}

		for identity, fd := range extractFuncDocs(fset, filename, file) {
			if existing, ok := funcs[identity]; ok {
				existing.Examples = append(existing.Examples, fd.Examples...)
			} else {
				funcs[identity] = fd
			}
		}
	}

	identities := make([]string, 0, len(funcs))
	nameCounts := make(map[string]int, len(funcs))
	for identity := range funcs {
		identities = append(identities, identity)
		nameCounts[funcs[identity].Name]++
	}
	sort.Strings(identities)
	expectedExamples := make(map[string]struct{}, len(funcs))
	for _, identity := range identities {
		fd := funcs[identity]
		if len(fd.Examples) > 0 {
			expectedExamples[exampleDirectoryName(fd, nameCounts[fd.Name] > 1)] = struct{}{}
		}
	}
	if err := cleanGeneratedExamples(examplesDir, expectedExamples); err != nil {
		return err
	}
	for _, identity := range identities {
		fd := funcs[identity]
		sort.Slice(fd.Examples, func(i, j int) bool {
			return fd.Examples[i].Line < fd.Examples[j].Line
		})

		if err := writeMain(examplesDir, fd, modPath, nameCounts[fd.Name] > 1); err != nil {
			return err
		}

	}

	return nil
}

// findRoot anchors generation to the root module from either the root or docs directory.
func findRoot() (string, error) {
	wd, err := os.Getwd()
	if err != nil {
		return "", fmt.Errorf("get working directory: %w", err)
	}
	if fileExists(filepath.Join(wd, "go.mod")) {
		return wd, nil
	}
	parent := filepath.Join(wd, "..")
	if fileExists(filepath.Join(parent, "go.mod")) {
		return filepath.Clean(parent), nil
	}
	return "", fmt.Errorf("could not find project root")
}

// fileExists lets root discovery ignore candidate paths that are not present.
func fileExists(p string) bool { _, err := os.Stat(p); return err == nil }

// modulePath reads the canonical import prefix so generated code never hard-codes a checkout identity.
func modulePath(root string) (string, error) {
	data, err := os.ReadFile(filepath.Join(root, "go.mod"))
	if err != nil {
		return "", err
	}

	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "module ") {
			return strings.TrimSpace(strings.TrimPrefix(line, "module ")), nil
		}
	}

	return "", fmt.Errorf("module path not found in go.mod")
}

//
// ------------------------------------------------------------
// Data models
// ------------------------------------------------------------
//

// FuncDoc captures the metadata needed to render one documented function.
type FuncDoc struct {
	Name        string
	Receiver    string
	Group       string
	Description string
	Examples    []Example
}

// Example captures an executable snippet and its source location.
type Example struct {
	FuncName string
	File     string
	Label    string
	Line     int
	Code     string
}

//
// ------------------------------------------------------------
// Example extraction
// ------------------------------------------------------------
//

var exampleHeader = regexp.MustCompile(`(?i)^\s*Example:\s*(.*)$`)
var groupHeader = regexp.MustCompile(`(?i)^\s*@group\s+(.+)$`)

type docLine struct {
	text string
	pos  token.Pos
}

// extractFuncDocs limits generation to exported declarations and keys methods by receiver to prevent collisions.
func extractFuncDocs(
	fset *token.FileSet,
	filename string,
	file *ast.File,
) map[string]*FuncDoc {

	out := map[string]*FuncDoc{}

	for _, decl := range file.Decls {
		fn, ok := decl.(*ast.FuncDecl)
		if !ok || fn.Doc == nil {
			continue
		}

		name := fn.Name.Name
		if !ast.IsExported(name) {
			continue
		}
		receiver := receiverName(fn)

		out[funcIdentity(receiver, name)] = &FuncDoc{
			Name:        name,
			Receiver:    receiver,
			Group:       extractGroup(fn.Doc),
			Description: extractFuncDescription(fn.Doc),
			Examples:    extractBlocks(fset, filename, name, fn),
		}
	}

	return out
}

// receiverName returns the named receiver so method docs remain distinct from root functions.
func receiverName(fn *ast.FuncDecl) string {
	if fn.Recv == nil || len(fn.Recv.List) == 0 {
		return ""
	}
	receiver := fn.Recv.List[0].Type
	if pointer, ok := receiver.(*ast.StarExpr); ok {
		receiver = pointer.X
	}
	if identifier, ok := receiver.(*ast.Ident); ok {
		return identifier.Name
	}
	return ""
}

// funcIdentity creates the stable key used to keep methods and functions distinct.
func funcIdentity(receiver, name string) string {
	if receiver == "" {
		return name
	}
	return receiver + "." + name
}

// extractGroup honors the documentation grouping convention and places untagged APIs in Other.
func extractGroup(group *ast.CommentGroup) string {
	lines := docLines(group)

	for _, dl := range lines {
		trimmed := strings.TrimSpace(dl.text)
		if m := groupHeader.FindStringSubmatch(trimmed); m != nil {
			return strings.TrimSpace(m[1])
		}
	}

	return "Other"
}

// extractFuncDescription stops before directives and examples so generated prose is not duplicated.
func extractFuncDescription(group *ast.CommentGroup) string {
	lines := docLines(group)
	var desc []string

	for _, dl := range lines {
		trimmed := strings.TrimSpace(dl.text)

		// Stop before Example or @group
		if exampleHeader.MatchString(trimmed) || groupHeader.MatchString(trimmed) {
			break
		}

		if len(desc) == 0 && trimmed == "" {
			continue
		}

		desc = append(desc, dl.text)
	}

	for len(desc) > 0 && strings.TrimSpace(desc[len(desc)-1]) == "" {
		desc = desc[:len(desc)-1]
	}

	return strings.Join(desc, "\n")
}

// docLines preserves token positions while normalizing line-comment prefixes for parsing.
func docLines(group *ast.CommentGroup) []docLine {
	var lines []docLine

	for _, c := range group.List {
		text := c.Text

		if strings.HasPrefix(text, "//") {
			line := strings.TrimPrefix(text, "//")
			if strings.HasPrefix(line, " ") {
				line = line[1:]
			}
			if strings.HasPrefix(line, "\t") {
				line = line[1:]
			}
			lines = append(lines, docLine{
				text: line,
				pos:  c.Slash,
			})
		}
	}

	return lines
}

// extractBlocks parses every labeled example in source order without interpreting its Go code.
func extractBlocks(
	fset *token.FileSet,
	filename, funcName string,
	fn *ast.FuncDecl,
) []Example {

	var out []Example
	lines := docLines(fn.Doc)

	var label string
	var collected []string
	var startLine int
	inExample := false

	flush := func() {
		if len(collected) == 0 {
			return
		}

		out = append(out, Example{
			FuncName: funcName,
			File:     filename,
			Label:    label,
			Line:     startLine,
			Code:     strings.Join(collected, "\n"),
		})

		collected = nil
		label = ""
		inExample = false
	}

	for _, dl := range lines {
		raw := dl.text
		trimmed := strings.TrimSpace(raw)

		if m := exampleHeader.FindStringSubmatch(trimmed); m != nil {
			flush()
			inExample = true
			label = strings.TrimSpace(m[1])
			startLine = fset.Position(dl.pos).Line
			continue
		}

		if !inExample {
			continue
		}

		collected = append(collected, raw)
	}

	flush()
	return out
}

// selectPackage picks the primary package to document.
// Strategy:
//  1. If only one package exists, use it.
//  2. Prefer the non-"main" package with the most files.
//  3. Fall back to the first package alphabetically.
func selectPackage(pkgs map[string]*ast.Package) (string, error) {
	if len(pkgs) == 0 {
		return "", fmt.Errorf("no packages found")
	}

	if len(pkgs) == 1 {
		for name := range pkgs {
			return name, nil
		}
	}

	type candidate struct {
		name  string
		count int
	}

	candidates := make([]candidate, 0, len(pkgs))
	for name, pkg := range pkgs {
		candidates = append(candidates, candidate{
			name:  name,
			count: len(pkg.Files),
		})
	}

	sort.Slice(candidates, func(i, j int) bool {
		if candidates[i].count == candidates[j].count {
			return candidates[i].name < candidates[j].name
		}
		return candidates[i].count > candidates[j].count
	})

	for _, cand := range candidates {
		if cand.name != "main" {
			return cand.name, nil
		}
	}

	return candidates[0].name, nil
}

//
// ------------------------------------------------------------
// Write ./examples/<func>/main.go
// ------------------------------------------------------------
//

// writeMain formats one consumer-facing executable per documented API identity.
func writeMain(base string, fd *FuncDoc, importPath string, nameCollides bool) error {
	if len(fd.Examples) == 0 {
		return nil
	}

	if importPath == "" {
		return fmt.Errorf("import path cannot be empty")
	}

	dir := filepath.Join(base, exampleDirectoryName(fd, nameCollides))
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}

	var buf bytes.Buffer

	buf.WriteString("//go:build ignore\n")
	buf.WriteString("// +build ignore\n\n")
	buf.WriteString(generatedMarker + "\n\n")

	buf.WriteString("package main\n\n")

	imports := map[string]bool{
		importPath: true,
	}

	for _, ex := range fd.Examples {
		if strings.Contains(ex.Code, "fmt.") {
			imports["fmt"] = true
		}
		if strings.Contains(ex.Code, "strings.") {
			imports["strings"] = true
		}
		if strings.Contains(ex.Code, "os.") {
			imports["os"] = true
		}
		if strings.Contains(ex.Code, "filepath.") {
			imports["path/filepath"] = true
		}
		if strings.Contains(ex.Code, "godump.") {
			imports["github.com/goforj/godump"] = true
		}
	}

	writeImports(&buf, imports)

	buf.WriteString("// main keeps this documented example executable so API drift fails during compilation.\n")
	buf.WriteString("func main() {\n")

	if fd.Description != "" {
		for _, line := range strings.Split(fd.Description, "\n") {
			buf.WriteString("\t// " + line + "\n")
		}
		buf.WriteString("\n")
	}

	for _, ex := range fd.Examples {
		if ex.Label != "" {
			buf.WriteString("\t// Example: " + ex.Label + "\n")
		}

		ex.Code = strings.TrimLeft(ex.Code, "\n")

		for _, line := range strings.Split(ex.Code, "\n") {
			if strings.TrimSpace(line) == "" {
				buf.WriteString("\n")
			} else {
				buf.WriteString("\t" + line + "\n")
			}
		}
	}

	buf.WriteString("}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format example %s: %w", funcIdentity(fd.Receiver, fd.Name), err)
	}
	return os.WriteFile(filepath.Join(dir, "main.go"), formatted, 0o644)
}

// cleanGeneratedExamples removes obsolete generated entrypoints while preserving manual examples.
func cleanGeneratedExamples(base string, expected map[string]struct{}) error {
	entries, err := os.ReadDir(base)
	if err != nil {
		return fmt.Errorf("read examples directory: %w", err)
	}
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		if _, keep := expected[entry.Name()]; keep {
			continue
		}
		path := filepath.Join(base, entry.Name(), "main.go")
		contents, err := os.ReadFile(path)
		if errors.Is(err, os.ErrNotExist) {
			continue
		}
		if err != nil {
			return fmt.Errorf("read generated example %s: %w", path, err)
		}
		if !bytes.Contains(contents, []byte(generatedMarker)) {
			continue
		}
		if err := os.Remove(path); err != nil {
			return fmt.Errorf("remove obsolete generated example %s: %w", path, err)
		}
	}
	return nil
}

// exampleDirectoryName qualifies colliding methods without renaming established unique examples.
func exampleDirectoryName(fd *FuncDoc, nameCollides bool) string {
	if nameCollides && fd.Receiver != "" {
		return strings.ToLower(fd.Receiver + "-" + fd.Name)
	}
	return strings.ToLower(fd.Name)
}

// writeImports renders stable standard-library and third-party import groups.
func writeImports(buf *bytes.Buffer, imports map[string]bool) {
	if len(imports) == 1 {
		for path := range imports {
			fmt.Fprintf(buf, "import %q\n\n", path)
		}
		return
	}

	standard := make([]string, 0, len(imports))
	thirdParty := make([]string, 0, len(imports))
	for path := range imports {
		firstSegment := strings.Split(path, "/")[0]
		if strings.Contains(firstSegment, ".") {
			thirdParty = append(thirdParty, path)
			continue
		}
		standard = append(standard, path)
	}
	sort.Strings(standard)
	sort.Strings(thirdParty)

	buf.WriteString("import (\n")
	for _, path := range standard {
		fmt.Fprintf(buf, "\t%q\n", path)
	}
	if len(standard) > 0 && len(thirdParty) > 0 {
		buf.WriteString("\n")
	}
	for _, path := range thirdParty {
		fmt.Fprintf(buf, "\t%q\n", path)
	}
	buf.WriteString(")\n\n")
}
