//go:build ignore
// +build ignore

// Code generated by docs/examplegen; DO NOT EDIT.

package main

import (
	"os"

	"github.com/goforj/env/v2"
)

// main keeps this documented example executable so API drift fails during compilation.
func main() {
	// GetMap parses trimmed key=value pairs separated by commas into a map.

	// Example: parse throttling config
	_ = os.Setenv("LIMITS", "read=10, write=5, burst=20")
	limits := env.GetMap("LIMITS", "")
	env.Dump(limits)
	// #map[string]string [
	//  "burst" => "20" #string
	//  "read"  => "10" #string
	//  "write" => "5" #string
	// ]

	// Example: returns empty map when unset or blank
	os.Unsetenv("LIMITS")
	limits = env.GetMap("LIMITS", "")
	env.Dump(limits)
	// #map[string]string []
}
