//go:build ignore
// +build ignore

// Code generated by docs/examplegen; DO NOT EDIT.

package main

import "github.com/goforj/env/v2"

// main keeps this documented example executable so API drift fails during compilation.
func main() {
	// IsEnvLoaded reports whether a Load or Reload completed successfully in this process.

	env.Dump(env.IsEnvLoaded())
	// #bool true  (after Load)
	// #bool false (otherwise)
}
