//go:build ignore
// +build ignore

// Code generated by docs/examplegen; DO NOT EDIT.

package main

import (
	"os"

	"github.com/goforj/env/v2"
)

// main keeps this documented example executable so API drift fails during compilation.
func main() {
	// Get returns the environment variable for key or fallback when empty.

	// Example: fallback when unset
	os.Unsetenv("DB_HOST")
	host := env.Get("DB_HOST", "localhost")
	env.Dump(host)
	// #string "localhost"

	// Example: prefer existing value
	_ = os.Setenv("DB_HOST", "db.internal")
	host = env.Get("DB_HOST", "localhost")
	env.Dump(host)
	// #string "db.internal"
}
