//go:build ignore
// +build ignore

// Code generated by docs/examplegen; DO NOT EDIT.

package main

import (
	"os"

	"github.com/goforj/env/v2"
)

// main keeps this documented example executable so API drift fails during compilation.
func main() {
	// GetEnum returns the environment value when allowed and fallback otherwise.

	// Example: accept only staged environments
	_ = os.Setenv("APP_ENV", "production")
	appEnv := env.GetEnum("APP_ENV", "local", []string{"local", "staging", "production"})
	env.Dump(appEnv)
	// #string "production"

	// Example: fallback when unset
	os.Unsetenv("APP_ENV")
	appEnv = env.GetEnum("APP_ENV", "local", []string{"local", "staging", "production"})
	env.Dump(appEnv)
	// #string "local"
}
